"""Initial migration

Revision ID: cd958a21b209
Revises: 
Create Date: 2025-04-06 21:03:37.473299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'cd958a21b209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Check if the 'user' table exists
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if 'user' not in inspector.get_table_names():
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=150), nullable=False),
            sa.Column('password', sa.String(length=150), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
        )

    # Other migration commands
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_task_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint('uq_task_title', ['title'])
        batch_op.create_check_constraint('ck_task_complete', 'complete IS NOT NULL')
        batch_op.drop_column('completed')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_task_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_task_title', type_='unique')
        batch_op.drop_constraint('ck_task_complete', type_='check')
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    # Drop the user table
    op.drop_table('user')

    # ### end Alembic commands ###
